unique_ids:
  assets:
    standard-page.html: VC3X5WS5OKWX3KWKLHR4STHLDVV2VMEH
    theme.css: T63XMLHSX6KEROOZPIYJMNQPC2Y3QHKH
  forms:
    Form1: FDJPLYQAS4XPPZHYMP5ASWPYBJFXF7RO
  modules: {}
  scripts: {}
  server_modules: {}
