unique_ids:
  assets:
    standard-page.html: VC3X5WS5OKWX3KWKLHR4STHLDVV2VMEH
    theme.css: T63XMLHSX6KEROOZPIYJMNQPC2Y3QHKH
  forms:
    Form1: FDJPLYQAS4XPPZHYMP5ASWPYBJFXF7RO
    Form1.ItemTemplate1: '1775857597854106102107355.0138'
  modules: {}
  scripts: {}
  server_modules:
    ServerModule1: '1775864361778404624672668.4517'
